### ISSUE TITLE
Fix/Remove link in the first section of UG

### ISSUE THREAD

**Issue by Zhilin-Huang** [AY1920S2-CS2113-T14-1/tp#194]
I think the links in the first section of UG is not actually working (at least not on my laptop). Maybe we should either fix or remove them.
![image](https://user-images.githubusercontent.com/31772358/79018257-f21c9080-7ba5-11ea-910e-1ed28ecb7492.png)

**Comment by g-lilian** [comment]
Oh! I know what's the problem... they were working before. I think it's because I added the numbers to the headers. Will fix.
